import type { Resume } from "./types";

export const MOCK_RESUMES: Resume[] = [
  {
    id: "r1",
    name: "Currículo Principal 2026",
    kind: "original",
    role: "Engenheiro de Software Sênior",
    area: "Tecnologia",
    language: "pt",
    updatedAt: "2026-07-10T14:32:00Z",
    analyses: 12,
    atsVersions: 3,
    fileType: "pdf",
  },
  {
    id: "r2",
    name: "Resume — International",
    kind: "original",
    role: "Senior Software Engineer",
    area: "Technology",
    language: "en",
    updatedAt: "2026-06-28T09:10:00Z",
    analyses: 8,
    atsVersions: 2,
    fileType: "docx",
  },
  {
    id: "r3",
    name: "ATS — Vaga Nubank",
    kind: "ats",
    role: "Tech Lead Backend",
    area: "Fintech",
    language: "pt",
    updatedAt: "2026-07-15T18:05:00Z",
    analyses: 4,
    atsVersions: 1,
    fileType: "pdf",
  },
  {
    id: "r4",
    name: "ATS — Product Engineer",
    kind: "ats",
    role: "Product Engineer",
    area: "SaaS",
    language: "en",
    updatedAt: "2026-07-02T11:45:00Z",
    analyses: 6,
    atsVersions: 1,
    fileType: "pdf",
  },
];
